name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animated_list:
    git: https://github.com/vaetas/animated_list.git
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.3
  http: ^0.13.5
  intl: ^0.18.0
  rxdata:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
