name: rxdata
description: RxData for Riverpod
version: 1.0.0
homepage: https://github.com/vaetas/rxdata

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  state_notifier_test: ^0.0.9

flutter:
